---
- name: Run Docker Image
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Pull Docker Image
      command: docker pull adolphsa/fleet_farm_logo:0.0.2
      register: pull_output

    - name: Run Docker Image
      command: docker run -it adolphsa/fleet_farm_logo:0.0.2
      when: pull_output.rc == 0
